services:
  type: web
  name: esgi-heroku-nodejs
  env: node
  buildCommand: npm install
  startCommand: node ./bin/www
  envVars:
    - key: DATABASE_URL
      fromDatabase: bpdb
      property: connectionString

databases:
  name: bpdb
  plan: free
