services:
  - type: web
    plan: free
    name: esgi-heroku-nodejs
    env: node
    branch: main
    region: frankfurt
    buildCommand: npm install
    startCommand: node ./bin/www
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bpdb
          property: connectionString

databases:
  - name: bpdb
    region: frankfurt
    plan: free
